version: "3.3"

services:

  traefik:
    image: "traefik:v2.2"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.webudp.address=:80/udp"
      - "--entrypoints.websecureudp.address=:443/udp"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--certificatesresolvers.myresolver.acme.dnschallenge=true"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.provider=ovh"
      - "--certificatesresolvers.myresolver.acme.email=TYPEYOUREMAILHERE"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--accesslog=true"
      - "--accesslog.filepath=/var/log/traefik-access.log"
      - "--accesslog.bufferingsize=10"
    ports:
      - "80:80"
      - "80:80/udp"
      - "443:443"
      - "127.0.0.1:8080:8080"
    environment:
      - "OVH_ENDPOINT=ovh-eu"
      - "OVH_APPLICATION_KEY=PASTEYOURKEYHERE"
      - "OVH_APPLICATION_SECRET=PASTEYOURSECRETHERE"
      - "OVH_CONSUMER_KEY=PASTEYOURKEYHERE"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/var/log:/var/log"
    networks:
      - frontbridge
      
networks:
  frontbridge:
    external: true
